package org.caulfield.lib.faces.sso.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.8 Generated source
 * version: 2.2
 * <p>
 */
@WebService(name = "sso", targetNamespace = "http://sso.am.ejb.caulfield.org/")
public interface SSO {

  /**
   *
   * @param uuid
   * @return returns org.caulfield.ejb.am.sso.SSOCookie
   */
  @WebMethod
  public SSOCookie findCookieUser(@WebParam(name = "uuid") String uuid);

  /**
   *
   * @param oauthConsumerKey
   * @return returns org.caulfield.ejb.am.sso.SSOCookie
   */
  @WebMethod
  public SSOCookie findCookieOauth(@WebParam(name = "oauth_consumer_key") String oauthConsumerKey);

  /**
   *
   * @param uuid
   */
  @WebMethod
  public void clearCookie(@WebParam(name = "uuid") String uuid);

  /**
   *
   * @param username
   */
  @WebMethod
  public void updateLastSeen(@WebParam(name = "username") String username);

  /**
   *
   * @param cookie
   * @return returns boolean
   */
  @WebMethod
  public boolean setCookie(@WebParam(name = "cookie") SSOCookie cookie);

  /**
   *
   * @param username
   * @param password
   * @return returns java.lang.String
   */
  @WebMethod
  public String addCookie(@WebParam(name = "username") String username,
                          @WebParam(name = "password") String password);

}
